#pragma config(Sensor, in6,    TipperPot,      sensorPotentiometer)
#pragma config(Sensor, in7,    MogoPot,        sensorPotentiometer)
#pragma config(Sensor, in8,    LiftPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  RightEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftEnc,        sensorQuadEncoder)
#pragma config(Motor,  port2,           Swing,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Mogo,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LeftFrontDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LeftRearDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RightRearDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           RightFrontDrive, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Tipper,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

//PROTOTYPES
void drivePID(int driveDistance);
void turnLeftPID(int driveDistance);
void turnRightPID(int driveDistance);

//GLOBALS
int liftHeight = 0;
int swingHeight = 0;


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

//autos
task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	int driveDistance = 250;
	turnLeftPID(250);
	//drivePID(driveDistance);
	//drivePID(-driveDistance);
	// Remove this function call once you have "real" code.
	//AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
task liftPID()
{

}
void turnLeftPID(int driveDistance)
{
	int errorRight = 0;
	int prevErrorRight = 0;
	int errorLeft = 0;
	int prevErrorLeft = 0;
	int integralRight = 0;
	int integralLeft = 0;
	int derivativeRight = 0;
	int derivativeLeft = 0;
	int speedRight;
	int speedLeft;
	int driveLeft;
	int driveRight;
	float kP = .1;
	float kI = .0003;
	float kD = .005;
	driveLeft = -driveDistance;
	driveRight = driveDistance;
	SensorValue[LeftEnc] = 0;
	SensorValue[RightEnc] = 0;


	errorRight = driveRight - SensorValue[RightEnc];
	prevErrorRight = driveRight - SensorValue[RightEnc];
	errorLeft = driveLeft - SensorValue[LeftEnc];
	prevErrorLeft = driveLeft - SensorValue[LeftEnc];

	while ( abs(errorRight) != 0 && abs(errorLeft)!= 0)
	{
		errorLeft = driveRight - SensorValue[LeftEnc];
		errorRight = driveLeft - SensorValue[RightEnc];
		integralRight = integralRight + errorRight;
		integralLeft = integralLeft + errorLeft;
		if (errorLeft == 0 || errorRight == 0)
		{
			integralRight = 0;
			integralLeft = 0;
		}
		derivativeRight = errorRight - prevErrorRight;
		prevErrorRight = errorRight;
		derivativeLeft = errorLeft - prevErrorLeft;
		prevErrorLeft = errorLeft;

		speedRight = errorRight*kP + integralRight*kI + derivativeRight*kD;
		speedLeft = errorLeft * kP + integralLeft*kI + derivativeLeft*kD;
		motor[LeftFrontDrive] = -speedLeft;
		motor[RightFrontDrive] = speedRight;
		motor[LeftRearDrive] = -speedLeft;
		motor[RightRearDrive] = speedRight;

		wait1Msec(15);
	}
}

void turnRightPID(int driveDistance)
{

}
void drivePID(int driveDistance)
{
	int errorRight = 0;
	int prevErrorRight = 0;
	int errorLeft = 0;
	int prevErrorLeft = 0;
	int integralRight = 0;
	int integralLeft = 0;
	int derivativeRight = 0;
	int derivativeLeft = 0;
	int speedRight;
	int speedLeft;
	float kP = .9;
	float kI = .00001;
	float kD = .005;

	//values for turn
	/*float kP = .1;
	float kI = .0003;
	float kD = .005;
	*/
	SensorValue[LeftEnc] = 0;
	SensorValue[RightEnc] = 0;

	if(driveDistance > 0)
	{
		errorRight = driveDistance - SensorValue[RightEnc];
		prevErrorRight = driveDistance - SensorValue[RightEnc];
		errorLeft = driveDistance - SensorValue[LeftEnc];
		prevErrorLeft = driveDistance - SensorValue[LeftEnc];

		while ( abs(errorRight) != 0 && abs(errorLeft)!= 0)
		{
			errorLeft = driveDistance - SensorValue[LeftEnc];
			errorRight = driveDistance - SensorValue[RightEnc];
			integralRight = integralRight + errorRight;
			integralLeft = integralLeft + errorLeft;
			if (errorLeft == 0 || errorRight == 0)
			{
				integralRight = 0;
				integralLeft = 0;
			}
			derivativeRight = errorRight - prevErrorRight;
			prevErrorRight = errorRight;
			derivativeLeft = errorLeft - prevErrorLeft;
			prevErrorLeft = errorLeft;

			speedRight = errorRight*kP + integralRight*kI + derivativeRight*kD;
			speedLeft = errorLeft * kP + integralLeft*kI + derivativeLeft*kD;
			motor[LeftFrontDrive] = speedLeft;
			motor[RightFrontDrive] = speedRight;
			motor[LeftRearDrive] = speedLeft;
			motor[RightRearDrive] = speedRight;

			wait1Msec(15);
		}

		//run in reverse for a bit to make sure movement
		//is stopped
		/*
		motor[LeftFrontDrive] = -25;
		motor[RightFrontDrive] = -25;
		motor[LeftRearDrive] = -25;
		motor[RightRearDrive] = -25;
		wait1Msec(400);
		*/
	}
	else
	{
		errorRight = driveDistance - SensorValue[RightEnc];
		prevErrorRight = driveDistance - SensorValue[RightEnc];
		errorLeft = driveDistance - SensorValue[LeftEnc];
		prevErrorLeft = driveDistance - SensorValue[LeftEnc];

		while ( abs(errorRight) != 0 && abs(errorLeft) != 0)
		{
			errorLeft = driveDistance - SensorValue[LeftEnc];
			errorRight = driveDistance - SensorValue[RightEnc];
			integralRight = integralRight + errorRight;
			integralLeft = integralLeft + errorLeft;
			if (errorLeft == 0 || errorRight == 0)
			{
				integralRight = 0;
				integralLeft = 0;
			}
			derivativeRight = errorRight - prevErrorRight;
			prevErrorRight = errorRight;
			derivativeLeft = errorLeft - prevErrorLeft;
			prevErrorLeft = errorLeft;

			speedRight = errorRight*kP + integralRight*kI + derivativeRight*kD;
			speedLeft = errorLeft * kP + integralLeft*kI + derivativeLeft*kD;
			motor[LeftFrontDrive] = speedLeft;
			motor[RightFrontDrive] = speedRight;
			motor[LeftRearDrive] = speedLeft;
			motor[RightRearDrive] = speedRight;

			wait1Msec(15);
		}

		//run in reverse for a bit to make sure movement
		//is stopped
		/*
		motor[LeftFrontDrive] = 15;
		motor[RightFrontDrive] = 15;
		motor[LeftRearDrive] = 15;
		motor[RightRearDrive] = 15;
		wait1Msec(800);
		*/
	}
	//kill motors
	motor[LeftFrontDrive] = 0;
	motor[RightFrontDrive] = 0;
	motor[LeftRearDrive] = 0;
	motor[RightRearDrive] = 0;
	wait1Msec(500);
	return;
}

task usercontrol()
{

	// User control code here, inside the loop
	int y;
	int x;
	int threshhigh = 100;
	int threshlow = 20;

	while (true)
	{

		if(abs(vexRT[Ch3]) >= threshhigh)
		{
			y = vexRT[Ch3] * .8;
		}
		else if(abs(vexRT[Ch3]) <= threshlow)
		{
			y = 0;
		}
		else
		{
			y = vexRT[Ch3];
		}

		if(abs(vexRT[Ch1]) >= threshhigh)
		{
			x = vexRT[Ch1] * .8;
		}
		else if(abs(vexRT[Ch1]) <= threshlow)
		{
			x = 0;
		}
		else
		{
			x = vexRT[Ch1];
		}

		motor[LeftFrontDrive] = x + y;
		motor[RightFrontDrive] = -x + y;
		motor[LeftRearDrive] = x + y;
		motor[RightRearDrive] = -x + y;

		if(vexRT[Btn6U] == 1)
		{
			motor[Lift] = 127;
		}
		else if(vexRT[Btn6D] == 1)
		{
			motor[Lift] = -127;
		}
		else
		{
			motor[Lift] = 0;
		}

		if(vexRT[Btn5U] == 1)
		{
			motor[Swing] = 127;
		}
		else if(vexRT[Btn5D] == 1)
		{
			motor[Swing] = -127;
		}
		else
		{
			motor[Swing] = 0;
		}

		if(vexRT[Btn8U] == 1)
		{
			motor[Mogo] = 127;
		}
		else if(vexRT[Btn8D] == 1)
		{
			motor[Mogo] = -127;
		}
		else
		{
			motor[Mogo] = 0;
		}
	}
}
