#pragma config(Sensor, in1,    LeftPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    RightPot,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LimitUp,        sensorTouch)
#pragma config(Sensor, dgtl2,  LimitDown,      sensorTouch)
#pragma config(Motor,  port1,           intake,        tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftOutsideD,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           LeftInsideD,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           RightInsideD,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           RightOutsideD, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           LeftOutsideL,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           LeftInsideL,   tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           RightInsideL,  tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           RightOutsideL, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          Swing,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"



//TODO check new controls
//TODO Compensate for backward angle sensors
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/
int numCones = 0;

task ConeStack ()
{
	// lift up cone and use the lift value * numCones in order to find height that adds cone to base
	// make button that subtracts to numCones if one falls off
	// will reset the numCones when we drop off the base
	int ConeSize = 20;
	// numCones is the current number of stacked cones and ConeSize is the number of ticks it takes to get to next cone
	// added value is the value we want to go above the previous cone that was already added
	int coneHeight = numCones * ConeSize;
	int liftValue = coneHeight + 500;

	motor[intake] = 30;

	// liftng up the lift and rotating the claw thing
	while(SensorValue[LeftPot] < liftValue)
	{
		// 300 is lower value point at which the swinging arm will reach the same time as the lift
		if(SensorValue[LimitUp] != 1 && SensorValue[LeftPot] > (300 + coneHeight))
		{
			motor[Swing] = 127;
		}
		else
		{
			motor[Swing] = 20;
		}

		if(SensorValue[LeftPot] < SensorValue[RightPot])
		{
			motor[LeftInsideL] = 127;
			motor[RightInsideL] = 127*.8;
			motor[LeftOutsideL] = 127;
			motor[RightOutsideL] = 127*.8;
		}
		else if(SensorValue[LeftPot] > SensorValue[RightPot])
		{
			motor[LeftInsideL] = 127*.8;
			motor[RightInsideL] = 127;
			motor[LeftOutsideL] = 127*.8;
			motor[RightOutsideL] = 127;
		}
		else
		{
			motor[LeftInsideL] = 127;
			motor[RightInsideL] = 127;
			motor[LeftOutsideL] = 127;
			motor[RightOutsideL] = 127;
		}
	}

	// reset all motors to rest
	motor[LeftInsideL] = 0;
	motor[RightInsideL] = 0;
	motor[LeftOutsideL] = 0;
	motor[RightOutsideL] = 0;

	// drop cone
	motor[intake] = -127;
	wait1Msec(500);
	motor[intake] = 0;
	wait1Msec(10);

	// resetting the lift to start
	while(SensorValue[LeftPot] > 0)
	{
		// 300 is lower value point at which the swinging arm will reach the same time as the lift
		if(SensorValue[LimitDown] != 1)
		{
			motor[Swing] = -127;
		}
		else
		{
			motor[Swing] = 0;
		}

		if(SensorValue[LeftPot] < SensorValue[RightPot])
		{
			motor[LeftInsideL] = -127;
			motor[RightInsideL] = -127*.8;
			motor[LeftOutsideL] = -127;
			motor[RightOutsideL] = -127*.8;
		}
		else if(SensorValue[LeftPot] > SensorValue[RightPot])
		{
			motor[LeftInsideL] = -127*.8;
			motor[RightInsideL] = -127;
			motor[LeftOutsideL] = -127*.8;
			motor[RightOutsideL] = -127;
		}
		else
		{
			motor[LeftInsideL] = -127;
			motor[RightInsideL] = -127;
			motor[LeftOutsideL] = -127;
			motor[RightOutsideL] = -127;
		}
	}

	numCones++;

	EndTimeSlice();
	stopTask(ConeStack);
}





void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		int thresh = 10;
		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................
		
		
			
		//Back/Forth function
		if (abs(vecRT[Ch3]) >= thresh){ //if displacement above threshhold, move
			if (vecRT[Ch3] > 0){ //if positive
				if(abs(vexRT[Ch3]) >= 100) //limit to max of 100
				{
					motor[LeftOutsideD] = vexRT[100];
					motor[LeftInsideD] = vexRT[100];
					motor[RightOutsideD] = vexRT[100];
					motor[RightInsideD] = vexRT[100];
				}
				else //go controlled speed if below 100
				{
					motor[LeftOutsideD] = vexRT[Ch3];
					motor[LeftInsideD] = vexRT[Ch3];
					motor[RightOutsideD] = vexRT[Ch3];
					motor[RightInsideD] = vexRT[Ch3];
				}
			}
			else{ //negative
				if(abs(vexRT[Ch3]) >= 100) //limit to max of 100
				{
					motor[LeftOutsideD] = vexRT[-100];
					motor[LeftInsideD] = vexRT[-100];
					motor[RightOutsideD] = vexRT[-100];
					motor[RightInsideD] = vexRT[-100];
				}
				else //go controlled speed if below 100
				{
					motor[LeftOutsideD] = vexRT[-1 *Ch3];
					motor[LeftInsideD] = vexRT[-1 *Ch3];
					motor[RightOutsideD] = vexRT[-1 *Ch3];
					motor[RightInsideD] = vexRT[-1 *Ch3];
				}	
			}
		}
		else{ //if not above threshold, don't move
			motor[LeftOutsideD] = 0;
			motor[LeftInsideD] = 0;
		}
		
		
		
		//Turning function
		if (abs(vecRT[Ch2]) >= thresh){ //if displacement above threshhold, move
			if (vecRT[Ch2] > 0){ //if right
				if(abs(vexRT[Ch2]) >= 100) //limit to max of 100
				{
					motor[LeftOutsideD] = vexRT[100];
					motor[LeftInsideD] = vexRT[100];
					motor[RightOutsideD] = vexRT[-100];
					motor[RightInsideD] = vexRT[-100];
				}
				else //go controlled speed if below 100
				{
					motor[LeftOutsideD] = vexRT[Ch2];
					motor[LeftInsideD] = vexRT[Ch2];
					motor[RightOutsideD] = vexRT[-1 * Ch2];
					motor[RightInsideD] = vexRT[-1 * Ch2];
				}
			}
			else{ //left
				if(abs(vexRT[Ch2]) >= 100) //limit to max of 100
				{
					motor[LeftOutsideD] = vexRT[100];
					motor[LeftInsideD] = vexRT[100];
					motor[RightOutsideD] = vexRT[-100];
					motor[RightInsideD] = vexRT[-100];
				}
				else //go controlled speed if below 100
				{
					motor[LeftOutsideD] = vexRT[-1 *Ch2];
					motor[LeftInsideD] = vexRT[-1 *Ch2];
					motor[RightOutsideD] = vexRT[Ch2];
					motor[RightInsideD] = vexRT[Ch2];
				}	
			}
		}
		else{ //if not above threshold, don't move
			motor[LeftOutsideD] = 0;
			motor[LeftInsideD] = 0;
			motor[RightOutsideD] = 0;
			motor[RightInsideD] = 0;
		}
		
		
		
		if(vexRT[Btn8U] == 1)
		{
			startTask (ConeStack);
		}
		else if(vexRT[Btn8D] == 1)
		{
			numCones--;
		}



		if(vexRT[Btn6U] == 1)
		{
		motor[LeftOutsideL] = 127;
		motor[LeftInsideL] = 127;
		motor[RightInsideL] = 127;
		motor[RightOutsideL] = 127;
		}
		else if (vexRT[Btn6D] == 1)
		{
		motor[LeftOutsideL] = -127;
		motor[LeftInsideL] = -127;
		motor[RightInsideL] = -127;
		motor[RightOutsideL] = -127;
		}
		else
		{
		motor[LeftOutsideL] = 0;
		motor[LeftInsideL] = 0;
		motor[RightInsideL] = 0;
		motor[RightOutsideL] = 0;
		}


	}
}
